// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


float leitura1;
float leitura10;
float leitura11;
float leitura12;
float leitura13;
float leitura14;
float leitura15;
float leitura16;
float leitura17;
float leitura18;
float leitura19;
float leitura2;
float leitura20;
float leitura21;
float leitura22;
float leitura23;
float leitura24;
float leitura25;
float leitura26;
float leitura27;
float leitura28;
float leitura29;
float leitura3;
float leitura30;
float leitura4;
float leitura5;
float leitura6;
float leitura7;
float leitura8;
float leitura9;

void initProperties(){

  ArduinoCloud.addProperty(leitura1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura10, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura11, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura12, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura13, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura14, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura15, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura16, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura17, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura18, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura19, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura20, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura21, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura22, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura23, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura24, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura25, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura26, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura27, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura28, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura29, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura30, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura4, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura5, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura6, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura7, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura8, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leitura9, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
